# Cloudflare Workers CLI (Wrangler) Configuration
#
# See <https://developers.cloudflare.com/workers/wrangler/configuration/> for
# available options and their meanings. Not all possible options are shown in
# this template!
#
# SPDX-FileCopyrightText: 2021-2022 Junde Yhi <junde@yhi.moe>
# SPDX-License-Identifier: CC0-1.0

main = "src/index.ts"
compatibility_date = "2022-10-01"
compatibility_flags = [ "url_standard" ]
minify = true

# You can change the name of worker.
name = "purl-workers"

# If using Workers KV, fill its ID below.
# kv_namespaces = [
#   { binding = "kv", id = "" }
# ]
