name: Deploy
on:
  - push
  - repository_dispatch

jobs:
  deploy:
    name: Deploy with Workers
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v3

      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
