name: Test
on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v3

      - name: Set Up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Run Lints
        run: npm run lint
